baseURL = "https://localhost/"
languageCode = "es-ES"
title = "My New Hugo Site"
publishDir = "docs"
[params]
schedule1 = "Lun-Vie: 8am a 2pm"
schedule2 = "Sab-Dom: 11am a 4pm"
phone = "1 (829) 787-0797"
bannerline1 = "Ahora puedes sentir la energía"
bannerline2 = "Inicia tu día con"
bannerline3 = "un café negro"
bannerbutton = "Comprar"
bannerimage = "../img/header-bg.jpg"
videolink = "https://www.youtube.com/watch?v=ARA0AxrnHdM"
videoline1 = "Vive el proceso d hacer café."
videoline2 = "Trasmitimos nuestro"
videoline3 = "proceso de hacer café"
videoline4 = "Estamos aquí para escuchar sus opiniones"
videoline5 = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp or incididunt ut labore et dolore magna aliqua. Ut enim ad minim."
videosignature = "img/signature.png"
carteline1 = "¿Que tipo de café te servimos?"
carteline2 = "Estamos extremadamente enamorados del sistema ecológico."
